name: Java CI with Gradle

on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle - Forge
        run: ./gradlew :forge:build
      - name: Build with Gradle - Fabric
        run: ./gradlew :fabric:build
      - name: Upload Artifacts - Forge
        uses: actions/upload-artifact@v2
        with:
          name: forge_artifacts
          path: ./forge/build/libs/
      - name: Upload Artifacts - Fabric
        uses: actions/upload-artifact@v2
        with:
          name: fabric_artifacts
          path: ./fabric/build/libs/
      